version: '2'
services:
  acquire-it-api.db:
    image: postgres
  acquire-it-api.web:
    build: .
    command: bundle exec rails s -p 4001 -b '0.0.0.0'
    volumes:
      - .:/acquire-it
    ports:
      - "4001:4001"
    depends_on:
      - acquire-it-api.db
